# Fig pre block. Keep at the top of this file.
[[ -f "$HOME/.fig/shell/zshrc.pre.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.pre.zsh"

if [[ -s "${HOME}/.zprezto/init.zsh" ]]
then
  source "${HOME}/.zprezto/init.zsh"
fi

source ~/.zshrc.d/env.zsh
source ~/.zshrc.d/path.zsh
source ~/.zshrc.d/common.zsh
source ~/.zshrc.d/aliases.zsh
source ~/.zshrc.d/prompt.zsh
source ~/.zshrc.d/insided.zsh
source ~/.zshrc.d/git.zsh
source ~/.zshrc.d/completion.zsh
source ~/.zshrc.d/zplug.zsh

# Fig post block. Keep at the bottom of this file.
[[ -f "$HOME/.fig/shell/zshrc.post.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.post.zsh"
